# Generated by Django 3.2.8 on 2022-03-23 05:46

from django.db import migrations

from api_product.constants import ProductData


def init_data_product(apps, schema_editor):
    product_model = apps.get_model("api_product", "Product")
    category_model = apps.get_model("api_product", "Category")
    eraser_category = category_model.objects.filter(name="ERASER").first()
    note_category = category_model.objects.filter(name="STICKY NOTE").first()

    products = []

    for eraser in ProductData.erasers:
        products.append(product_model(id=eraser['id'], name=eraser['name'], category=eraser_category))

    for note in ProductData.notes:
        products.append(product_model(id=note['id'], name=note['name'], category=note_category))

    product_model.objects.bulk_create(products)


def delete_all_data(apps, schema_editor):
    product_model = apps.get_model("api_product", "Product")
    product_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0004_migrate_category'),
    ]

    operations = [
        migrations.RunPython(init_data_product, delete_all_data)
    ]
