# Generated by Django 3.2.8 on 2022-04-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0008_migrate_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
