# Generated by Django 3.2.8 on 2022-03-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0002_alter_account_role'),
    ]

    operations = [
    ]
