# Generated by Django 3.2.8 on 2022-03-11 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0003_migrate_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(70), django.core.validators.MinValueValidator(18)]),
        ),
    ]
