# Generated by Django 3.2.8 on 2022-03-25 17:18
import os

from django.contrib.auth.hashers import make_password
from django.db import migrations


def initial_admin_data(apps, schema_editor):
    account_model = apps.get_model("api_account", "Account")
    role_model = apps.get_model("api_account", "Role")

    ras_role = role_model.objects.filter(name="RASPBERRY").first()

    admin = account_model(is_superuser=False, first_name="PI", last_name="RASPBERRY", is_staff=True, username="pi",
                          email="ras@gmail.com",
                          password=make_password(os.getenv('DEFAULT_RASPBERRY_PASSWORD')),
                          role=ras_role)

    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api_account', '0006_migrate_user'),
    ]

    operations = [
        migrations.RunPython(initial_admin_data, migrations.RunPython.noop)
    ]
